version: "3.7"

services:
  postgres:
    image: "postgres:11.2-alpine"
    ports:
      - "5432:5432"
    labels:
      traefik.enable: "false"
    volumes:
      - "./.docker-compose/postgres/data/:/var/lib/postgresql/data/"
      - "./.docker-compose/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    logging:
      options:
        max-size: 1m
