version: "3.7"

services:
  postgres:
    image: "postgres:11.2-alpine"
    ports:
      - "5432:5432"
    labels:
      traefik.enable: "false"
    volumes:
      - "./_services/postgres/data/:/var/lib/postgresql/data/"
      - "./_services/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    environment:
      DATABASE_URL: "postgresql://postgres:password@0.0.0.0/"
      POSTGRES_PASSWORD: "password"
    logging:
      options:
        max-size: 1m
