# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.6.3"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rom", "~> 5.0"
gem "rom-sql", "~> 3.0"
gem "puma", "~> 3.12"
gem "roda", "~> 3.20"
