---
images:
  - "us.gcr.io/$PROJECT_ID/base:latest"
  - "us.gcr.io/$PROJECT_ID/base:$SHORT_SHA"
  - "us.gcr.io/$PROJECT_ID/$FUNCTION_ID:latest"
  - "us.gcr.io/$PROJECT_ID/$FUNCTION_ID:$SHORT_SHA"
timeout: "5m"
steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull us.gcr.io/$PROJECT_ID/base:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull us.gcr.io/$PROJECT_ID/$FUNCTION_ID:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/build"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/push"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/ship"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
