---
images:
  - "us.gcr.io/$PROJECT_ID/base:latest"
  - "us.gcr.io/$PROJECT_ID/base:$SHORT_SHA"
  - "us.gcr.io/$PROJECT_ID/$_SERVICE_ID:latest"
  - "us.gcr.io/$PROJECT_ID/$_SERVICE_ID:$SHORT_SHA"
timeout: "5m"
steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull us.gcr.io/$PROJECT_ID/base:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull us.gcr.io/$PROJECT_ID/$_SERVICE_ID:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/build $PROJECT_ID $SHORT_SHA $_SERVICE_ID"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/push $PROJECT_ID $SHORT_SHA $_SERVICE_ID"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/ship $PROJECT_ID $SHORT_SHA $_SERVICE_ID"
