---
images:
  - "us.gcr.io/$PROJECT_ID/base:latest"
  - "us.gcr.io/$PROJECT_ID/base:$SHORT_SHA"
  - "us.gcr.io/$PROJECT_ID/mtgjson-import:latest"
  - "us.gcr.io/$PROJECT_ID/mtgjson-import:$SHORT_SHA"
timeout: "5m"
steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull us.gcr.io/$PROJECT_ID/base:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull us.gcr.io/$PROJECT_ID/mtgjson-import:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/build mtgjson-import"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/ship mtgjson-import"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
      - "CLOUDSDK_COMPUTE_ZONE=us-west1-a"
