# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    # TODO: bundler env variables --jobs=4 --retry=3
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          DEPLOY_ENV: "development"
          RACK_ENV: "development"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST: "postgres"
          POSTGRES_URI: "postgresql:///resources"
      - image: circleci/postgres:11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./_base/Gemfile.lock" }}
      - run:
          name: setup services
          command: bin/local-setup
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "./_base/Gemfile.lock" }}
      - run:
          name: run tooling
          command: "bin/local-check"
