# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.6.3"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rom", "~> 5.0"
gem "rom-sql", "~> 3.0"
gem "roda", "~> 3.20"
gem "falcon", "~> 0.30.0"
gem "pg", "~> 1.1"
gem "rake", "~> 12.3"
gem "semantic_logger", "~> 4.5"
gem "stackdriver", "~> 0.15.3", require: [
  "stackdriver",
  "google/cloud/debugger",
  "google/cloud/trace",
  "google/cloud/error_reporting",
  "google/cloud/logging"
]

gem "pry", "~> 0.12.2"

gem "pry-doc", "~> 1.0"

gem "pry-coolline", "~> 0.2.5"

gem "pry-remote", "~> 0.1.8"

gem "pry-stack_explorer", "~> 0.4.9"

gem "pry-syntax-hacks", "~> 0.0.6"

gem "pry-rescue", "~> 1.5"

gem "pry-inline", "~> 1.0"

gem "pry-loudmouth", "~> 0.1.0"

gem "pry-auto_benching.rb", "~> 3.2"
