# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "puma", "~> 3.12"
gem "rom", "~> 5.0"
gem "rom-sql", "~> 3.0"

gem "jruby-pg", "~> 0.1"
